# SPDX-License-Identifier: CC0-1.0
#
# Nintendo DS Gospel reader built with BlocksDS.

BLOCKSDS ?= /opt/wonderful/thirdparty/blocksds/core

NAME          := gospel_nds
GAME_TITLE    := Evangelio NDS
GAME_SUBTITLE := CEE Gospel Reader
GAME_AUTHOR   := Angel R.

LIBS    := -lnds9
LIBDIRS := $(BLOCKSDS)/libs/libnds

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
