#!/usr/bin/env python3
# SPDX-License-Identifier: CC0-1.0

from __future__ import annotations

import json
import pathlib
import unicodedata


ROOT = pathlib.Path(__file__).resolve().parents[1]
RES = ROOT / "res"
OUT = ROOT / "source" / "gospel_data.c"

BOOKS = [
    ("mateo", "Mateo", "Mt"),
    ("marcos", "Marcos", "Mc"),
    ("lucas", "Lucas", "Lc"),
    ("juan", "Juan", "Jn"),
]

TRANSLATE = str.maketrans(
    {
        "«": '"',
        "»": '"',
        "“": '"',
        "”": '"',
        "‘": "'",
        "’": "'",
        "—": "-",
        "–": "-",
        "…": "...",
        "º": "o",
        "ª": "a",
        "|": "/",
    }
)


def console_text(value: str) -> str:
    value = value.translate(TRANSLATE)
    value = value.replace("ñ", "\x7f").replace("Ñ", "\x7f")
    value = unicodedata.normalize("NFKD", value)
    value = value.encode("ascii", "ignore").decode("ascii")
    return " ".join(value.split())


def c_string(value: str) -> str:
    escaped = []
    for char in value:
        if char == "\\":
            escaped.append("\\\\")
        elif char == '"':
            escaped.append('\\"')
        elif char == "\x7f":
            escaped.append("\\177")
        else:
            escaped.append(char)
    return f'"{"".join(escaped)}"'


def main() -> None:
    verses = []
    books = []
    chapter_tables = []

    for key, name, abbr in BOOKS:
        with (RES / f"{key}.json").open(encoding="utf-8") as fh:
            data = json.load(fh)[key]

        first = len(verses)
        chapter_counts = []
        for chapter_s in sorted(data, key=lambda n: int(n)):
            chapter = int(chapter_s)
            chapter_data = data[chapter_s]
            count = 0
            for verse_s in sorted(chapter_data, key=lambda n: int(n)):
                verse = int(verse_s)
                verses.append((name, abbr, chapter, verse, console_text(chapter_data[verse_s])))
                count += 1
            chapter_counts.append(count)

        table_name = f"{key}_chapter_counts"
        chapter_tables.append((table_name, chapter_counts))
        books.append((name, abbr, first, len(verses) - first, len(chapter_counts), table_name))

    lines = [
        "// SPDX-License-Identifier: CC0-1.0",
        "// Generated by tools/generate_gospel_data.py. Do not edit by hand.",
        "",
        '#include "gospel_data.h"',
        "",
    ]

    for table_name, counts in chapter_tables:
        joined = ", ".join(str(count) for count in counts)
        lines.append(f"static const uint8_t {table_name}[] = {{{joined}}};")

    lines.extend(
        [
            "",
            "const GospelBook gospel_books[] = {",
        ]
    )
    for name, abbr, first, count, chapter_count, table_name in books:
        lines.append(
            f"    {{{c_string(name)}, {c_string(abbr)}, {first}, {count}, {chapter_count}, {table_name}}},"
        )
    lines.extend(
        [
            "};",
            "",
            f"const uint16_t gospel_book_count = {len(books)};",
            f"const uint16_t gospel_verse_count = {len(verses)};",
            "",
            "const GospelVerse gospel_verses[] = {",
        ]
    )
    for name, abbr, chapter, verse, text in verses:
        lines.append(
            f"    {{{c_string(name)}, {c_string(abbr)}, {chapter}, {verse}, {c_string(text)}}},"
        )
    lines.extend(
        [
            "};",
            "",
            "int gospel_find_verse(int book_index, int chapter, int verse)",
            "{",
            "    if (book_index < 0 || book_index >= gospel_book_count)",
            "        return -1;",
            "",
            "    const GospelBook *book = &gospel_books[book_index];",
            "    if (chapter < 1 || chapter > book->chapter_count)",
            "        return -1;",
            "    if (verse < 1 || verse > book->verses_per_chapter[chapter - 1])",
            "        return -1;",
            "",
            "    int index = book->first_verse;",
            "    for (int ch = 1; ch < chapter; ch++)",
            "        index += book->verses_per_chapter[ch - 1];",
            "    return index + verse - 1;",
            "}",
            "",
            "int gospel_first_verse_in_chapter(int book_index, int chapter)",
            "{",
            "    return gospel_find_verse(book_index, chapter, 1);",
            "}",
            "",
            "int gospel_next_verse_index(int verse_index)",
            "{",
            "    if (verse_index < 0)",
            "        return 0;",
            "    return (verse_index + 1) % gospel_verse_count;",
            "}",
            "",
            "int gospel_prev_verse_index(int verse_index)",
            "{",
            "    if (verse_index <= 0)",
            "        return gospel_verse_count - 1;",
            "    return verse_index - 1;",
            "}",
        ]
    )

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
